[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
opacity = 0.7
blur = true
dynamic_padding = true
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 20

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.2


[colors.cursor]
text = "0x1e1e2e"
cursor = "0xf5e0dc"

[colors.selection]
text       = "0x1e1e2e"
background = "0xf5e0dc"

[colors.primary]
background = "0x1e1e2e"   # nền
foreground = "0xcdd6f4"   # chữ

[colors.normal]
black   = "0x45475a"
red     = "0xf38ba8"
green   = "0xa6e3a1"
yellow  = "0xf9e2af"
blue    = "0x89b4fa"
magenta = "0xf5c2e7"
cyan    = "0x94e2d5"
white   = "0xbac2de"

[colors.bright]
black   = "0x585b70"
red     = "0xf38ba8"
green   = "0xa6e3a1"
yellow  = "0xf9e2af"
blue    = "0x89b4fa"
magenta = "0xf5c2e7"
cyan    = "0x94e2d5"
white   = "0xf5f5f5"

# Key bindings
[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullscreen"

# Tmux integration
[[keyboard.bindings]]
key = "N"
mods = "Command"
command = { program = "tmux", args = ["new-window"] }

[[keyboard.bindings]]
key = "T"
mods = "Command"
command = { program = "tmux", args = ["new-session"] }
